import type { Project, Post, TrendItem, SearchTerm, Professional, VideoTask } from '@/types'

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Clínica Habitus',
    slug: 'clinica-habitus',
    description: 'Clínica de saúde integrativa',
    niche: 'Saúde integrativa',
    segment: 'Saúde',
    primaryColor: '#6B2D3E',
    secondaryColor: '#FAF7F2',
    accentColor: '#C9A96E',
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    toneOfVoice: 'Acolhedor, profissional e integrativo',
    copyPersonality: 'Educativo e empático',
    forbiddenWords: ['cura garantida', 'milagre', 'cure'],
    forbiddenTopics: [],
    defaultCTAs: ['Agende sua consulta', 'Saiba mais', 'Reserve sua vaga'],
    defaultHashtags: ['#saudeintegrativa', '#clinicahabitus', '#bemestar'],
    contentPillars: ['Saúde integrativa', 'Nutrição', 'Ozonioterapia', 'Bem-estar'],
    targetAudience: 'Adultos de 30-55 anos interessados em saúde preventiva',
    brandKeywords: ['integrative', 'wellness', 'holistic'],
    competitors: [],
    niches: ['saúde integrativa', 'nutrição', 'ozonioterapia', 'estética'],
    searchKeywords: ['saúde integrativa', 'ozonioterapia'],
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
    _count: { posts: 42, professionals: 3 },
  },
  {
    id: 'proj-2',
    name: 'Odília Mello Nutricionista',
    slug: 'odilia-mello',
    description: 'Nutricionista especializada em emagrecimento',
    niche: 'Nutrição',
    segment: 'Saúde',
    primaryColor: '#2D6B5A',
    secondaryColor: '#F0FAF7',
    accentColor: '#A8D5C5',
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    toneOfVoice: 'Educativo, empático e motivador',
    copyPersonality: 'Próxima e encorajadora',
    forbiddenWords: [],
    forbiddenTopics: [],
    defaultCTAs: ['Fale comigo', 'Agende sua consulta', 'Saiba mais'],
    defaultHashtags: ['#nutrição', '#emagrecimento', '#alimentacaosaudavel'],
    contentPillars: ['Nutrição', 'Emagrecimento', 'Receitas', 'Educação alimentar'],
    targetAudience: 'Mulheres de 25-50 anos querendo emagrecer com saúde',
    brandKeywords: [],
    competitors: [],
    niches: ['nutrição', 'emagrecimento', 'alimentação saudável'],
    searchKeywords: [],
    isActive: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
    _count: { posts: 28, professionals: 1 },
  },
  {
    id: 'proj-3',
    name: 'Salão Beleza Premium',
    slug: 'salao-beleza',
    description: 'Salão de beleza premium',
    niche: 'Beleza',
    segment: 'Beleza',
    primaryColor: '#D4A0C0',
    secondaryColor: '#FDF5F9',
    accentColor: '#E8C8D8',
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    toneOfVoice: 'Leve, visual e comercial',
    copyPersonality: 'Inspirador e focado em transformação',
    forbiddenWords: [],
    forbiddenTopics: [],
    defaultCTAs: ['Agende seu horário', 'Conheça nossos serviços'],
    defaultHashtags: ['#beleza', '#cabelo', '#autoestima'],
    contentPillars: ['Cabelo', 'Unhas', 'Maquiagem', 'Transformações'],
    targetAudience: 'Mulheres de 18-45 anos',
    brandKeywords: [],
    competitors: [],
    niches: ['cabelo', 'unhas', 'maquiagem', 'tratamentos capilares'],
    searchKeywords: [],
    isActive: true,
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-02-01T00:00:00Z',
    _count: { posts: 35, professionals: 2 },
  },
]

const now = new Date()
const d = (offset: number) => new Date(now.getTime() + offset * 24 * 60 * 60 * 1000).toISOString()

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    projectId: 'proj-1',
    authorId: 'user-1',
    title: 'Benefícios da vitamina D na imunidade',
    theme: 'Saúde preventiva',
    format: 'REELS_INSTAGRAM',
    networks: ['INSTAGRAM'],
    status: 'PENDING_APPROVAL',
    caption: 'Você sabia que a vitamina D é essencial para seu sistema imunológico? 🌟 Descubra os benefícios e como manter seus níveis ideais.',
    hashtags: ['#vitaminaD', '#imunidade', '#saudeintegrativa'],
    publishDate: d(3),
    createdAt: d(-2),
    updatedAt: d(-1),
  },
  {
    id: 'post-2',
    projectId: 'proj-1',
    authorId: 'user-1',
    title: 'O que é Ozonioterapia?',
    theme: 'Educativo',
    format: 'CAROUSEL_INSTAGRAM',
    networks: ['INSTAGRAM'],
    status: 'APPROVED',
    caption: 'A ozonioterapia é um tratamento que utiliza o ozônio medicinal para...',
    hashtags: ['#ozonioterapia', '#tratamento', '#saude'],
    publishDate: d(1),
    scheduledAt: d(1),
    createdAt: d(-5),
    updatedAt: d(-1),
  },
  {
    id: 'post-3',
    projectId: 'proj-2',
    authorId: 'user-2',
    title: '5 alimentos que aceleram o metabolismo',
    format: 'CAROUSEL_INSTAGRAM',
    networks: ['INSTAGRAM', 'FACEBOOK'],
    status: 'SCHEDULED',
    caption: 'Conheça os alimentos que vão te ajudar a emagrecer com saúde...',
    hashtags: ['#metabolismo', '#emagrecimento', '#nutrição'],
    publishDate: d(2),
    scheduledAt: d(2),
    createdAt: d(-3),
    updatedAt: d(-1),
  },
  {
    id: 'post-4',
    projectId: 'proj-3',
    authorId: 'user-1',
    title: 'Morena Iluminada — antes e depois',
    format: 'REELS_INSTAGRAM',
    networks: ['INSTAGRAM', 'TIKTOK'],
    status: 'WAITING_RECORDING',
    caption: 'Transformação incrível com a técnica morena iluminada...',
    hashtags: ['#morenaIluminada', '#cabelo', '#transformacao'],
    recordingDate: d(1),
    publishDate: d(5),
    createdAt: d(-1),
    updatedAt: d(0),
  },
  {
    id: 'post-5',
    projectId: 'proj-1',
    authorId: 'user-1',
    title: 'Estresse e queda de cabelo',
    format: 'REELS_INSTAGRAM',
    networks: ['INSTAGRAM'],
    status: 'IDEA',
    hashtags: [],
    createdAt: d(0),
    updatedAt: d(0),
  },
  {
    id: 'post-6',
    projectId: 'proj-2',
    authorId: 'user-2',
    title: 'Receita fit: bowl proteico',
    format: 'FEED_INSTAGRAM',
    networks: ['INSTAGRAM'],
    status: 'PUBLISHED',
    caption: 'Bowl proteico para começar bem o dia!',
    hashtags: ['#receitafit', '#proteina', '#bemestar'],
    publishDate: d(-2),
    publishedAt: d(-2),
    createdAt: d(-7),
    updatedAt: d(-2),
  },
]

export const MOCK_TRENDS: TrendItem[] = [
  {
    id: 'trend-1',
    projectId: 'proj-1',
    title: 'Queda de cabelo por deficiência de vitaminas',
    description: 'Buscas sobre queda de cabelo relacionadas a vitaminas bateram recorde esta semana.',
    niche: 'Saúde integrativa',
    trendScore: 87,
    source: 'Google Trends',
    reelsIdea: '"Você sabia que a falta de vitamina D pode causar queda de cabelo?" — mostre exames e explique os marcadores.',
    carouselIdea: '"5 vitaminas que previnem a queda de cabelo" — um slide por vitamina com fontes alimentares.',
    storiesIdea: '"Faz o teste: quantas vitaminas você consome?" — enquete interativa.',
    suggestedCaption: 'A queda de cabelo pode ter uma causa nutricional. Veja quais vitaminas investigar e como repor.',
    recommendedFormat: 'REELS_INSTAGRAM',
    whyItMatters: 'Tópico em alta com potencial de viralizção para clínicas de saúde.',
    addedToCalendar: false,
    validUntil: d(7),
    createdAt: d(0),
  },
  {
    id: 'trend-2',
    projectId: 'proj-1',
    title: 'Ozonioterapia para dores crônicas',
    description: 'Interesse crescente em terapias alternativas para dor.',
    niche: 'Ozonioterapia',
    trendScore: 74,
    source: 'TikTok Trending',
    reelsIdea: '"Ozonioterapia funciona para artrose?" — mostre o antes e depois de pacientes (com autorização).',
    carouselIdea: '"Para que serve a ozonioterapia" — 6 indicações com explicação científica.',
    storiesIdea: '"Você conhece a ozonioterapia?" — enquete + CTA para consulta.',
    whyItMatters: 'Tendência crescente em medicina integrativa.',
    addedToCalendar: false,
    validUntil: d(14),
    createdAt: d(0),
  },
  {
    id: 'trend-3',
    projectId: 'proj-2',
    title: 'Alimentação anti-inflamatória',
    description: 'Busca por dietas anti-inflamatórias cresceu 45% na última semana.',
    niche: 'Nutrição',
    trendScore: 92,
    source: 'Google Trends',
    reelsIdea: '"O que comer para reduzir a inflamação em 7 dias" — série de vídeos curtos.',
    carouselIdea: '"10 alimentos anti-inflamatórios que você já tem em casa".',
    storiesIdea: '"Sua alimentação inflama ou cura? Teste rápido."',
    suggestedCaption: 'A alimentação anti-inflamatória pode transformar sua saúde de dentro para fora.',
    recommendedFormat: 'CAROUSEL_INSTAGRAM',
    whyItMatters: 'Alto volume de busca, fácil de produzir conteúdo educativo.',
    addedToCalendar: false,
    validUntil: d(5),
    createdAt: d(0),
  },
]

export const MOCK_SEARCH_TERMS: SearchTerm[] = [
  {
    id: 'st-1',
    projectId: 'proj-1',
    term: 'queda de cabelo pode ser falta de vitamina',
    niche: 'Saúde integrativa',
    monthlySearches: 40500,
    difficulty: 32,
    isFeatured: true,
    reelsIdea: 'Explique a conexão entre deficiência nutricional e queda capilar em 60s.',
    carouselIdea: '"5 vitaminas que investigar quando tem queda de cabelo"',
    captionSuggestion: 'A queda de cabelo nem sempre tem causa genética. Veja o que investigar primeiro.',
    googlePostIdea: 'Promoção: avaliação completa para queda capilar',
    createdAt: d(0),
    updatedAt: d(0),
  },
  {
    id: 'st-2',
    projectId: 'proj-1',
    term: 'por que sinto cansaço mesmo dormindo bem',
    niche: 'Saúde integrativa',
    monthlySearches: 27200,
    difficulty: 28,
    isFeatured: false,
    reelsIdea: '"Por que você se cansa mesmo dormindo 8h?" — explique causas hormonais e nutricionais.',
    carouselIdea: '"7 causas do cansaço crônico que a medicina convencional ignora"',
    captionSuggestion: 'Dormir bem e ainda acordar cansado pode ser sinal de algo que precisa de atenção.',
    createdAt: d(0),
    updatedAt: d(0),
  },
  {
    id: 'st-3',
    projectId: 'proj-2',
    term: 'como emagrecer sem passar fome',
    niche: 'Nutrição',
    monthlySearches: 60500,
    difficulty: 45,
    isFeatured: true,
    reelsIdea: '"O método que faz você emagrecer sem ficar com fome" — explique saciedade e volume alimentar.',
    carouselIdea: '"Emagrecer sem fome: 5 estratégias que funcionam de verdade"',
    captionSuggestion: 'Emagrecer não precisa ser sinônimo de sofrer. Veja como fazer de forma inteligente.',
    createdAt: d(0),
    updatedAt: d(0),
  },
]

export const MOCK_PROFESSIONALS: Professional[] = [
  {
    id: 'prof-1',
    projectId: 'proj-1',
    name: 'Dra. Ana Paula',
    email: 'ana@habitus.com',
    accessToken: 'token-ana-123',
    avatarUrl: undefined,
    bio: 'Médica integrativa especializada em ozonioterapia',
    createdAt: d(-30),
  },
  {
    id: 'prof-2',
    projectId: 'proj-2',
    name: 'Dra. Odília Mello',
    email: 'odilia@nutriodilia.com',
    accessToken: 'token-odilia-456',
    bio: 'Nutricionista CRN-9999',
    createdAt: d(-20),
  },
]

export const MOCK_VIDEO_TASKS: VideoTask[] = [
  {
    id: 'vt-1',
    professionalId: 'prof-1',
    postId: 'post-5',
    title: 'Estresse e queda de cabelo',
    description: 'Explique a relação entre cortisol elevado e queda capilar. Use dados científicos simples.',
    recordingGuide: 'Grave em pé, fundo neutro ou consultório. Luz natural pela janela. Roupa profissional.',
    suggestedDuration: 60,
    toneOfVoice: 'Educativo e acolhedor',
    observations: 'Evitar termos técnicos demais. Falar de forma próxima.',
    deadline: d(3),
    status: 'PENDING',
    createdAt: d(-1),
    updatedAt: d(-1),
  },
  {
    id: 'vt-2',
    professionalId: 'prof-2',
    title: 'Como montar um prato equilibrado',
    description: 'Mostre na prática como dividir o prato entre proteínas, carboidratos e vegetais.',
    recordingGuide: 'Grave na cozinha com os alimentos em mãos. Pode ser uma montagem ao vivo.',
    suggestedDuration: 45,
    toneOfVoice: 'Didático e animado',
    deadline: d(2),
    status: 'PENDING',
    createdAt: d(-2),
    updatedAt: d(-2),
  },
]
